export interface OAuthConfig {
  name: string
  clientId: string
  clientSecret: string
  authorizationUrl: string
  tokenUrl: string
  scopes: string[]
  icon: string
  color: string
  abbr: string
  category: string
  description: string
}

export const CONNECTOR_CONFIG: Record<string, OAuthConfig> = {
  GMAIL: {
    name: "Gmail",
    clientId: process.env.GOOGLE_CLIENT_ID ?? "",
    clientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
    authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    scopes: [
      "https://www.googleapis.com/auth/gmail.readonly",
      "https://www.googleapis.com/auth/gmail.send",
    ],
    icon: "📧",
    color: "bg-cache-err",
    abbr: "Gm",
    category: "Communication",
    description: "Read and search emails. Send emails with approval.",
  },
  GOOGLE_DRIVE: {
    name: "Google Drive",
    clientId: process.env.GOOGLE_CLIENT_ID ?? "",
    clientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
    authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    scopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
    ],
    icon: "📁",
    color: "bg-bc-700",
    abbr: "GD",
    category: "Knowledge",
    description: "Index documents. Read selected files.",
  },
  GOOGLE_CALENDAR: {
    name: "Google Calendar",
    clientId: process.env.GOOGLE_CLIENT_ID ?? "",
    clientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
    authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    scopes: ["https://www.googleapis.com/auth/calendar.readonly"],
    icon: "📅",
    color: "bg-bc-700",
    abbr: "GC",
    category: "Productivity",
    description: "Read calendar events and schedules.",
  },
  SLACK: {
    name: "Slack",
    clientId: process.env.SLACK_CLIENT_ID ?? "",
    clientSecret: process.env.SLACK_CLIENT_SECRET ?? "",
    authorizationUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    scopes: ["channels:read", "channels:history", "users:read", "chat:write"],
    icon: "💬",
    color: "bg-bc-accent",
    abbr: "Sl",
    category: "Communication",
    description: "Read channels and messages. Post with approval.",
  },
  GITHUB: {
    name: "GitHub",
    clientId: process.env.GITHUB_CLIENT_ID ?? "",
    clientSecret: process.env.GITHUB_CLIENT_SECRET ?? "",
    authorizationUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    scopes: ["repo:status", "read:org", "read:user"],
    icon: "🐙",
    color: "bg-surface-muted",
    abbr: "GH",
    category: "Engineering",
    description: "Read repositories, PRs, and issues.",
  },
  JIRA: {
    name: "Jira",
    clientId: process.env.JIRA_CLIENT_ID ?? "",
    clientSecret: process.env.JIRA_CLIENT_SECRET ?? "",
    authorizationUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    scopes: ["read:jira-work", "read:jira-user", "offline_access"],
    icon: "🎯",
    color: "bg-bc-700",
    abbr: "Ji",
    category: "Engineering",
    description: "Read tickets and sprints. Create tickets with approval.",
  },
  NOTION: {
    name: "Notion",
    clientId: process.env.NOTION_CLIENT_ID ?? "",
    clientSecret: process.env.NOTION_CLIENT_SECRET ?? "",
    authorizationUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
    scopes: [],
    icon: "📓",
    color: "bg-surface-over",
    abbr: "No",
    category: "Knowledge",
    description: "Read pages, databases, and docs.",
  },
  SALESFORCE: {
    name: "Salesforce",
    clientId: process.env.SALESFORCE_CLIENT_ID ?? "",
    clientSecret: process.env.SALESFORCE_CLIENT_SECRET ?? "",
    authorizationUrl: "https://login.salesforce.com/services/oauth2/authorize",
    tokenUrl: "https://login.salesforce.com/services/oauth2/token",
    scopes: ["api", "refresh_token", "offline_access"],
    icon: "☁️",
    color: "bg-bc-700",
    abbr: "SF",
    category: "CRM",
    description: "Read and search CRM records.",
  },
  HUBSPOT: {
    name: "HubSpot",
    clientId: process.env.HUBSPOT_CLIENT_ID ?? "",
    clientSecret: process.env.HUBSPOT_CLIENT_SECRET ?? "",
    authorizationUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    scopes: ["crm.objects.contacts.read", "crm.objects.deals.read"],
    icon: "🧡",
    color: "bg-cache-miss",
    abbr: "HS",
    category: "CRM",
    description: "Read contacts, deals, and companies.",
  },
  ZENDESK: {
    name: "Zendesk",
    clientId: process.env.ZENDESK_CLIENT_ID ?? "",
    clientSecret: process.env.ZENDESK_CLIENT_SECRET ?? "",
    authorizationUrl: "https://subdomain.zendesk.com/oauth/authorizations/new",
    tokenUrl: "https://subdomain.zendesk.com/oauth/tokens",
    scopes: ["read"],
    icon: "🎧",
    color: "bg-cache-hit",
    abbr: "Zd",
    category: "CRM",
    description: "Read tickets and customer conversations.",
  },
  MICROSOFT_TEAMS: {
    name: "Microsoft Teams",
    clientId: process.env.MICROSOFT_CLIENT_ID ?? "",
    clientSecret: process.env.MICROSOFT_CLIENT_SECRET ?? "",
    authorizationUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    scopes: ["User.Read", "Team.ReadBasic.All", "Channel.ReadBasic.All", "Chat.Read"],
    icon: "💼",
    color: "bg-bc-accent",
    abbr: "MS",
    category: "Communication",
    description: "Read teams, channels, and chat messages.",
  },
  ONEDRIVE: {
    name: "OneDrive",
    clientId: process.env.MICROSOFT_CLIENT_ID ?? "",
    clientSecret: process.env.MICROSOFT_CLIENT_SECRET ?? "",
    authorizationUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    scopes: ["Files.Read", "Files.Read.All", "offline_access"],
    icon: "☁️",
    color: "bg-bc-700",
    abbr: "OD",
    category: "Knowledge",
    description: "Read and index files from OneDrive.",
  },
  CONFLUENCE: {
    name: "Confluence",
    clientId: process.env.JIRA_CLIENT_ID ?? "",
    clientSecret: process.env.JIRA_CLIENT_SECRET ?? "",
    authorizationUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    scopes: ["read:confluence-content.all", "offline_access"],
    icon: "📚",
    color: "bg-bc-700",
    abbr: "Cf",
    category: "Knowledge",
    description: "Read spaces, pages, and documentation.",
  },
}
