// Client-safe connector metadata. NO secrets here — safe to import in the browser.

export interface ConnectorMeta {
  key: string
  name: string
  iconSlug: string
  iconColor: string
  color: string
  abbr: string
  category: string
  description: string
  /** Scopes requested during OAuth — displayed to the user before connecting. */
  scopes: string[]
  /** Whether this connector supports write operations (requires human approval). */
  hasWriteActions: boolean
}

export const CONNECTOR_META: ConnectorMeta[] = [
  {
    key: "GMAIL",
    name: "Gmail",
    iconSlug: "gmail",
    iconColor: "EA4335",
    color: "bg-cache-err",
    abbr: "Gm",
    category: "Communication",
    description: "Search emails, summarize conversations, draft responses.",
    scopes: ["Read Email", "Search Email"],
    hasWriteActions: true,
  },
  {
    key: "GOOGLE_DRIVE",
    name: "Google Drive",
    iconSlug: "googledrive",
    iconColor: "4285F4",
    color: "bg-bc-700",
    abbr: "GD",
    category: "Knowledge",
    description: "Index documents, search files, read selected documents.",
    scopes: ["Read Files", "Search Files"],
    hasWriteActions: false,
  },
  {
    key: "GOOGLE_CALENDAR",
    name: "Google Calendar",
    iconSlug: "googlecalendar",
    iconColor: "4285F4",
    color: "bg-bc-700",
    abbr: "GC",
    category: "Productivity",
    description: "Read calendar events, check availability, and schedules.",
    scopes: ["Read Events"],
    hasWriteActions: false,
  },
  {
    key: "SLACK",
    name: "Slack",
    iconSlug: "slack",
    iconColor: "4A154B",
    color: "bg-bc-accent",
    abbr: "Sl",
    category: "Communication",
    description: "Search channels and messages. Post messages with approval.",
    scopes: ["Read Messages", "Search Messages"],
    hasWriteActions: true,
  },
  {
    key: "GITHUB",
    name: "GitHub",
    iconSlug: "github",
    iconColor: "181717",
    color: "bg-surface-muted",
    abbr: "GH",
    category: "Engineering",
    description: "Read repositories, PRs, and issues. Create issues with approval.",
    scopes: ["Read Repositories", "Read Issues", "Read PRs"],
    hasWriteActions: true,
  },
  {
    key: "JIRA",
    name: "Jira",
    iconSlug: "jira",
    iconColor: "0052CC",
    color: "bg-bc-700",
    abbr: "Ji",
    category: "Engineering",
    description: "Search tickets and sprints. Create and update tickets with approval.",
    scopes: ["Read Issues", "Search Issues"],
    hasWriteActions: true,
  },
  {
    key: "NOTION",
    name: "Notion",
    iconSlug: "notion",
    iconColor: "000000",
    color: "bg-surface-over",
    abbr: "No",
    category: "Knowledge",
    description: "Read pages, databases, and docs from your workspace.",
    scopes: ["Read Pages", "Search Content"],
    hasWriteActions: false,
  },
  {
    key: "CONFLUENCE",
    name: "Confluence",
    iconSlug: "confluence",
    iconColor: "172B4D",
    color: "bg-bc-700",
    abbr: "Cf",
    category: "Knowledge",
    description: "Read spaces, pages, and documentation.",
    scopes: ["Read Pages", "Read Spaces"],
    hasWriteActions: false,
  },
  {
    key: "SALESFORCE",
    name: "Salesforce",
    iconSlug: "salesforce",
    iconColor: "00A1E0",
    color: "bg-bc-700",
    abbr: "SF",
    category: "CRM",
    description: "Search and read CRM records, accounts, and opportunities.",
    scopes: ["Read CRM Records", "Search Records"],
    hasWriteActions: false,
  },
  {
    key: "HUBSPOT",
    name: "HubSpot",
    iconSlug: "hubspot",
    iconColor: "FF7A59",
    color: "bg-cache-miss",
    abbr: "HS",
    category: "CRM",
    description: "Read contacts, deals, and companies from HubSpot.",
    scopes: ["Read Contacts", "Read Deals"],
    hasWriteActions: false,
  },
  {
    key: "ZENDESK",
    name: "Zendesk",
    iconSlug: "zendesk",
    iconColor: "03363D",
    color: "bg-cache-hit",
    abbr: "Zd",
    category: "CRM",
    description: "Read tickets and customer conversations.",
    scopes: ["Read Tickets", "Search Tickets"],
    hasWriteActions: false,
  },
  {
    key: "MICROSOFT_TEAMS",
    name: "Microsoft Teams",
    iconSlug: "microsoftteams",
    iconColor: "6264A7",
    color: "bg-bc-accent",
    abbr: "MS",
    category: "Communication",
    description: "Search teams, channels, and chat messages.",
    scopes: ["Read Messages", "Read Channels"],
    hasWriteActions: true,
  },
  {
    key: "ONEDRIVE",
    name: "OneDrive",
    iconSlug: "microsoftonedrive",
    iconColor: "0078D4",
    color: "bg-bc-700",
    abbr: "OD",
    category: "Knowledge",
    description: "Search and read files from OneDrive.",
    scopes: ["Read Files", "Search Files"],
    hasWriteActions: false,
  },
]

export const CONNECTOR_CATEGORIES = [
  "All",
  "Engineering",
  "Knowledge",
  "Communication",
  "CRM",
  "Productivity",
]
